server:
  port: 8800

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pfa.production2023@gmail.com
    password: zaastubhxckgjppr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      maxFileSize: 5000000
      maxRequestSize: 20000000
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://localhost:3306/gdpr_dev
    username: root
    password:
        username: root
        password:
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    generateDdl: true
    showSql: true
    hibernate:
      ddlAuto: update

gdpr:
  env:
    uploadFolder: D:\said\Stage\Next_try\gdpr\public\upload-folder\fiches\
    admin:
      mail: saidelhabchi31@gmail.com