spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ADRESSE_EMAIL
    password: ACCESS_KEY_EMAIL
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      maxFileSize: 5000000
      maxRequestSize: 20000000

  datasource:
    url: jdbc:mysql://localhost:3306/gdpr_prod
    username: USERNAME
    password: PASSWORD

  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    generateDdl: true
    showSql: true
    hibernate:
      ddlAuto: update

gdpr:
  env:
    uploadFolderFiches: PATH_TO_FICHES_FORLDER
    uploadFolderAutorisations: PATH_TO_AUTORISATIONS_FORLDER
    admin:
      mail: ADRESSE_EMAIL_SAME